// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Variants = {};

var Record = {};

var Minimal_OptionalRecord = {};

exports.Variants = Variants;
exports.Record = Record;
exports.Minimal_OptionalRecord = Minimal_OptionalRecord;
/* No side effect */
