// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(x) {
  return x;
}

var M = {
  f: f
};

function toString(x) {
  return x;
}

var Z = {
  toString: toString
};

exports.M = M;
exports.Z = Z;
/* No side effect */
