// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Markdown = require("./Markdown.res.js");
var Core__Array = require("@rescript/core/src/Core__Array.res.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");

function title(txt, levelOpt) {
  var level = levelOpt !== undefined ? levelOpt : 1;
  return Markdown.heading(level)(txt);
}

function renderId(stripRootOpt, txt) {
  var stripRoot = stripRootOpt !== undefined ? stripRootOpt : false;
  if (stripRoot) {
    return txt.substring(txt.indexOf(".") + 1 | 0);
  } else {
    return txt;
  }
}

function deprecationWarning(md, deprecated) {
  return Markdown.append(md, Core__Option.mapOr(deprecated, Markdown.empty(), (function (deprecated) {
                    return Markdown.line(Markdown.line(Markdown.bold("DEPRECATED: " + deprecated)));
                  })));
}

function corretDocStringHeadingLevel(levelOpt, txt) {
  var level = levelOpt !== undefined ? levelOpt : 0;
  return txt.split("\n").map(function (line) {
                var trimmedLine = line.trimStart();
                var headingLevel = Markdown.headingLevel(trimmedLine);
                var diff = (level - headingLevel | 0) + 1 | 0;
                var missingLevels = headingLevel <= 0 || diff < 0 ? 0 : diff;
                return "#".repeat(missingLevels) + trimmedLine;
              }).join("\n");
}

function moduleDocs(md, levelOpt, docs) {
  var level = levelOpt !== undefined ? levelOpt : 0;
  return Markdown.append(md, Core__Array.reduce(docs, Markdown.empty(), (function (md, txt) {
                    return Markdown.append(md, Markdown.p(corretDocStringHeadingLevel(level, txt)));
                  })));
}

function renderItem(param, name, level, docstrings, deprecated, param$1, signature, _unit) {
  return moduleDocs(Markdown.appendO(deprecationWarning(title(name, level), deprecated), Core__Option.map(signature, (function (s) {
                        return Markdown.quote(s);
                      }))), level, docstrings);
}

function itemDoc(item) {
  switch (item.kind) {
    case "value" :
        var id = item.id;
        return renderItem(id, "let " + renderId(undefined, id), 3, item.docstrings, item.deprecated, undefined, item.signature, undefined);
    case "type" :
        var id$1 = item.id;
        return renderItem(id$1, "type " + renderId(undefined, id$1), 3, item.docstrings, item.deprecated, item.detail, item.signature, undefined);
    case "module" :
        var id$2 = item.id;
        return itemDocs(renderItem(id$2, "module " + renderId(undefined, id$2), 2, item.docstrings, item.deprecated, undefined, undefined, undefined), item.items);
    case "moduleAlias" :
        var id$3 = item.id;
        return itemDocs(renderItem(id$3, "module " + renderId(undefined, id$3) + " \`alias\`", 2, item.docstrings, undefined, undefined, undefined, undefined), item.items);
    
  }
}

function itemDocs(md, items) {
  return Markdown.append(md, Core__Array.reduce(items, Markdown.empty(), (function (md, item) {
                    return Markdown.append(md, itemDoc(item));
                  })));
}

function render(param) {
  return itemDocs(moduleDocs(deprecationWarning(title(param.name, undefined), param.deprecated), undefined, param.docstrings), param.items);
}

exports.render = render;
/* No side effect */
