// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");

function cmb(a, b) {
  if (a === "") {
    return b;
  } else if (b === "") {
    return a;
  } else {
    return a + b;
  }
}

function cmbO(a, b) {
  return Belt_Option.mapWithDefault(b, a, (function (b) {
                return cmb(a, b);
              }));
}

function empty() {
  return "";
}

function line(line$1) {
  return line$1 + "\n";
}

function bold(txt) {
  return "**" + txt + "**";
}

function p(txt) {
  return line(line(txt));
}

function quote(txt) {
  return p(txt.split("\n").map(function (line) {
                    return "> " + line;
                  }).join("\n"));
}

function h1(txt) {
  return p("# " + txt);
}

function h2(txt) {
  return p("## " + txt);
}

function h3(txt) {
  return p("### " + txt);
}

function h4(txt) {
  return p("#### " + txt);
}

function h5(txt) {
  return p("##### " + txt);
}

function h6(txt) {
  return p("###### " + txt);
}

exports.cmb = cmb;
exports.cmbO = cmbO;
exports.empty = empty;
exports.line = line;
exports.h1 = h1;
exports.h2 = h2;
exports.h3 = h3;
exports.h4 = h4;
exports.h5 = h5;
exports.h6 = h6;
exports.bold = bold;
exports.p = p;
exports.quote = quote;
/* No side effect */
